package ma.xpi.tlvtools.util

/**
 * Utility class for mapping ISO 18245 MCC (Merchant Category Code) codes to category names
 */
object MccMap {
    private val mccMap = mapOf(
        // Agricultural Services
        "0763" to "Agricultural Cooperatives",
        "0780" to "Horticultural Services",
        
        // Contracted Services
        "1520" to "General Contractors",
        "1711" to "Heating, Plumbing, Air Conditioning",
        "1731" to "Electrical Contractors",
        "1740" to "Masonry, Stonework, Tile Setting, Plastering",
        "1750" to "Carpentry Contractors",
        "1761" to "Roofing/Siding, Sheet Metal",
        "1771" to "Concrete Work Contractors",
        "1799" to "Special Trade Contractors",
        
        // Transportation Services
        "4111" to "Local/Suburban Commuter Passenger Transportation",
        "4112" to "Passenger Railways",
        "4121" to "Taxicabs and Limousines",
        "4131" to "Bus Lines",
        "4214" to "Motor Freight Carriers and Trucking",
        "4215" to "Courier Services",
        "4411" to "Cruise Lines",
        "4457" to "Boat Rentals and Leases",
        "4468" to "Marinas, Service and Supplies",
        "4511" to "Airlines, Air Carriers",
        "4582" to "Airports, Flying Fields",
        "4722" to "Travel Agencies, Tour Operators",
        "4784" to "Tolls/Bridge Fees",
        "4789" to "Transportation Services (Not Elsewhere Classified)",
        
        // Utility Services
        "4812" to "Telecommunication Equipment and Telephone Sales",
        "4814" to "Telecommunication Services",
        "4816" to "Computer Network Services",
        "4821" to "Telegraph Services",
        "4899" to "Cable and Other Pay Television Services",
        "4900" to "Utilities",
        
        // Retail Outlet Services
        "5013" to "Motor Vehicle Supplies and New Parts",
        "5021" to "Office and Commercial Furniture",
        "5039" to "Construction Materials (Not Elsewhere Classified)",
        "5044" to "Office, Photographic, Photocopy, and Microfilm Equipment",
        "5045" to "Computers and Computer Peripheral Equipment and Software",
        "5046" to "Commercial Equipment (Not Elsewhere Classified)",
        "5047" to "Medical, Dental, Ophthalmic, and Hospital Equipment and Supplies",
        "5051" to "Metal Service Centers",
        "5065" to "Electrical Parts and Equipment",
        "5072" to "Hardware, Equipment, and Supplies",
        "5074" to "Plumbing, Heating Equipment, and Supplies",
        "5085" to "Industrial Supplies (Not Elsewhere Classified)",
        "5094" to "Precious Stones and Metals, Watches and Jewelry",
        "5099" to "Durable Goods (Not Elsewhere Classified)",
        "5111" to "Stationery, Office Supplies, Printing and Writing Paper",
        "5122" to "Drugs, Drug Proprietaries, and Druggist Sundries",
        "5131" to "Piece Goods, Notions, and Other Dry Goods",
        "5137" to "Men's, Women's, and Children's Uniforms and Commercial Clothing",
        "5139" to "Commercial Footwear",
        "5169" to "Chemicals and Allied Products (Not Elsewhere Classified)",
        "5172" to "Petroleum and Petroleum Products",
        "5192" to "Books, Periodicals, and Newspapers",
        "5193" to "Florists Supplies, Nursery Stock, and Flowers",
        "5198" to "Paints, Varnishes, and Supplies",
        "5199" to "Nondurable Goods (Not Elsewhere Classified)",
        "5200" to "Home Supply Warehouse Stores",
        "5211" to "Lumber, Building Materials Stores",
        "5231" to "Glass, Paint, and Wallpaper Stores",
        "5251" to "Hardware Stores",
        "5261" to "Lawn and Garden Supply Stores",
        "5271" to "Mobile Home Dealers",
        "5300" to "Wholesale Clubs",
        "5309" to "Duty Free Stores",
        "5310" to "Discount Stores",
        "5311" to "Department Stores",
        "5331" to "Variety Stores",
        "5399" to "Miscellaneous General Merchandise",
        "5411" to "Grocery Stores, Supermarkets",
        "5422" to "Freezer and Locker Meat Provisioners",
        "5441" to "Candy, Nut, and Confectionery Stores",
        "5451" to "Dairy Products Stores",
        "5462" to "Bakeries",
        "5499" to "Miscellaneous Food Stores",
        "5511" to "Car and Truck Dealers (New & Used)",
        "5521" to "Car and Truck Dealers (Used Only)",
        "5531" to "Auto and Home Supply Stores",
        "5532" to "Automotive Tire Stores",
        "5533" to "Automotive Parts and Accessories Stores",
        "5541" to "Service Stations",
        "5542" to "Automated Fuel Dispensers",
        "5551" to "Boat Dealers",
        "5561" to "Camper, Recreational and Utility Trailer Dealers",
        "5571" to "Motorcycle Shops and Dealers",
        "5592" to "Motor Homes Dealers",
        "5598" to "Snowmobile Dealers",
        "5599" to "Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers",
        "5611" to "Men's and Boys' Clothing and Accessories Stores",
        "5621" to "Women's Ready-To-Wear Stores",
        "5631" to "Women's Accessory and Specialty Shops",
        "5641" to "Children's and Infants' Wear Stores",
        "5651" to "Family Clothing Stores",
        "5655" to "Sports and Riding Apparel Stores",
        "5661" to "Shoe Stores",
        "5681" to "Furriers and Fur Shops",
        "5691" to "Men's, Women's Clothing Stores",
        "5697" to "Tailors, Alterations",
        "5698" to "Wig and Toupee Stores",
        "5699" to "Miscellaneous Apparel and Accessory Shops",
        "5712" to "Furniture, Home Furnishings, and Equipment Stores",
        "5713" to "Floor Covering Stores",
        "5714" to "Drapery, Window Covering, and Upholstery Stores",
        "5718" to "Fireplace, Fireplace Screens, and Accessories Stores",
        "5719" to "Miscellaneous Home Furnishing Specialty Stores",
        "5722" to "Household Appliance Stores",
        "5732" to "Electronics Stores",
        "5733" to "Music Stores-Musical Instruments, Pianos, and Sheet Music",
        "5734" to "Computer Software Stores",
        "5735" to "Record Stores",
        "5811" to "Caterers",
        "5812" to "Eating Places, Restaurants",
        "5813" to "Drinking Places",
        "5814" to "Fast Food Restaurants",
        "5912" to "Drug Stores and Pharmacies",
        "5921" to "Package Stores-Beer, Wine, and Liquor",
        "5931" to "Used Merchandise and Secondhand Stores",
        "5932" to "Antique Shops",
        "5933" to "Pawn Shops",
        "5935" to "Wrecking and Salvage Yards",
        "5937" to "Antique Reproductions",
        "5940" to "Bicycle Shops",
        "5941" to "Sporting Goods Stores",
        "5942" to "Book Stores",
        "5943" to "Stationery Stores, Office, and School Supply Stores",
        "5944" to "Jewelry Stores, Watches, Clocks, and Silverware Stores",
        "5945" to "Hobby, Toy, and Game Shops",
        "5946" to "Camera and Photographic Supply Stores",
        "5947" to "Gift, Card, Novelty, and Souvenir Shops",
        "5948" to "Luggage and Leather Goods Stores",
        "5949" to "Sewing, Needlework, Fabric, and Piece Goods Stores",
        "5950" to "Glassware, Crystal Stores",
        "5960" to "Direct Marketing - Insurance Services",
        "5962" to "Direct Marketing - Travel",
        "5963" to "Door-To-Door Sales",
        "5964" to "Direct Marketing - Catalog Merchant",
        "5965" to "Direct Marketing - Combination Catalog and Retail Merchant",
        "5966" to "Direct Marketing - Outbound Tele",
        "5967" to "Direct Marketing - Inbound Tele",
        "5968" to "Direct Marketing - Subscription",
        "5969" to "Direct Marketing - Other",
        "5970" to "Artist's Supply and Craft Shops",
        "5971" to "Art Dealers and Galleries",
        "5972" to "Stamp and Coin Stores",
        "5973" to "Religious Goods Stores",
        "5975" to "Hearing Aids Sales and Supplies",
        "5976" to "Orthopedic Goods - Prosthetic Devices",
        "5977" to "Cosmetic Stores",
        "5978" to "Typewriter Stores",
        "5983" to "Fuel Dealers (Non Automotive)",
        "5992" to "Florists",
        "5993" to "Cigar Stores and Stands",
        "5994" to "News Dealers and Newsstands",
        "5995" to "Pet Shops, Pet Food, and Supplies",
        "5996" to "Swimming Pools Sales",
        "5997" to "Electric Razor Stores",
        "5998" to "Tent and Awning Shops",
        "5999" to "Miscellaneous Specialty Retail",
        
        // Service Providers
        "6010" to "Financial Institutions - Manual Cash Disbursements",
        "6011" to "Financial Institutions - Automated Cash Disbursements",
        "6012" to "Financial Institutions - Merchandise and Services",
        "6051" to "Non-Financial Institutions - Quasi Cash",
        "6211" to "Securities - Brokers and Dealers",
        "6300" to "Insurance Sales and Underwriting",
        "6513" to "Real Estate Agents and Managers - Rentals",
        "7011" to "Lodging - Hotels, Motels, and Resorts",
        "7012" to "Timeshares",
        "7032" to "Sporting and Recreational Camps",
        "7033" to "Trailer Parks, Campgrounds",
        "7210" to "Laundry, Cleaning, and Garment Services",
        "7211" to "Laundries",
        "7216" to "Dry Cleaners",
        "7217" to "Carpet and Upholstery Cleaning",
        "7221" to "Photographic Studios",
        "7230" to "Beauty and Barber Shops",
        "7251" to "Shoe Repair/Hat Cleaning",
        "7261" to "Funeral Services and Crematories",
        "7273" to "Dating/Escort Services",
        "7276" to "Tax Preparation Services",
        "7277" to "Counseling Services",
        "7278" to "Buying/Shopping Services",
        "7296" to "Clothing Rental",
        "7297" to "Massage Parlors",
        "7298" to "Health and Beauty Spas",
        "7299" to "Miscellaneous Personal Services",
        "7311" to "Advertising Services",
        "7321" to "Credit Reporting Agencies",
        "7333" to "Commercial Photography, Art and Graphics",
        "7338" to "Quick Copy, Repro, and Blueprint",
        "7339" to "Secretarial Support Services",
        "7342" to "Exterminating Services",
        "7349" to "Cleaning and Maintenance",
        "7361" to "Employment Agencies and Temp Help",
        "7372" to "Computer Programming",
        "7375" to "Information Retrieval Services",
        "7379" to "Computer Repair",
        "7392" to "Consulting, Public Relations",
        "7393" to "Detective Agencies",
        "7394" to "Equipment Rental",
        "7395" to "Photo Developing",
        "7399" to "Miscellaneous Business Services",
        "7512" to "Automobile Rental Agency",
        "7513" to "Truck/Utility Trailer Rentals",
        "7519" to "Recreational Vehicle Rentals",
        "7523" to "Parking Lots, Garages",
        "7531" to "Auto Body Repair Shops",
        "7534" to "Tire Retreading and Repair",
        "7535" to "Auto Paint Shops",
        "7538" to "Auto Service Shops",
        "7542" to "Car Washes",
        "7549" to "Towing Services",
        "7622" to "Electronics Repair Shops",
        "7623" to "A/C, Refrigeration Repair",
        "7629" to "Small Appliance Repair",
        "7631" to "Watch/Jewelry Repair",
        "7641" to "Furniture Repair, Refinishing",
        "7692" to "Welding Services",
        "7699" to "Miscellaneous Repair Shops",
        "7829" to "Picture/Video Production",
        "7832" to "Motion Picture Theaters",
        "7841" to "Video Tape Rental Stores",
        "7911" to "Dance Hall, Studios, Schools",
        "7922" to "Theatrical Ticket Agencies",
        "7929" to "Bands, Orchestras",
        "7932" to "Billiard/Pool Establishments",
        "7933" to "Bowling Alleys",
        "7941" to "Sports Clubs/Fields",
        "7991" to "Tourist Attractions and Exhibits",
        "7992" to "Golf Courses - Public",
        "7993" to "Video Amusement Game Supplies",
        "7994" to "Video Game Arcades",
        "7995" to "Betting/Casino Gambling",
        "7996" to "Amusement Parks/Carnivals",
        "7997" to "Country Clubs",
        "7998" to "Aquariums",
        "7999" to "Miscellaneous Recreation Services",
        "8011" to "Doctors",
        "8021" to "Dentists, Orthodontists",
        "8031" to "Osteopaths",
        "8041" to "Chiropractors",
        "8042" to "Optometrists",
        "8043" to "Opticians",
        "8049" to "Chiropodists, Podiatrists",
        "8050" to "Nursing/Personal Care",
        "8062" to "Hospitals",
        "8071" to "Medical and Dental Labs",
        "8099" to "Medical Services",
        "8111" to "Legal Services, Attorneys",
        "8211" to "Elementary, Secondary Schools",
        "8220" to "Colleges, Universities",
        "8241" to "Correspondence Schools",
        "8244" to "Business/Secretarial Schools",
        "8249" to "Vocational/Trade Schools",
        "8299" to "Educational Services",
        "8351" to "Child Care Services",
        "8398" to "Charitable Organizations",
        "8641" to "Civic, Social, Fraternal Associations",
        "8651" to "Political Organizations",
        "8661" to "Religious Organizations",
        "8675" to "Automobile Associations",
        "8699" to "Membership Organizations",
        "8734" to "Testing Laboratories",
        "8911" to "Architectural Services",
        "8931" to "Accounting/Bookkeeping Services",
        "8999" to "Professional Services",
        "9211" to "Court Costs, Including Alimony and Child Support",
        "9222" to "Fines",
        "9223" to "Bail and Bond Payments",
        "9311" to "Tax Payments",
        "9399" to "Government Services",
        "9402" to "Postal Services - Government Only",
        "9405" to "Intra-Government Purchases"
    )

    /**
     * Get the MCC category name for the given MCC code
     * @param code The MCC code
     * @return The MCC category name
     */
    fun getMccName(code: String): String {
        return mccMap[code] ?: "Unknown MCC ($code)"
    }
}
